import { _electron as electron } from 'playwright';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';

const root = await fs.mkdtemp(path.join(os.tmpdir(), 'explorer-compress-test-'));
const docs = path.join(root, 'Documents');
await fs.mkdir(path.join(docs, '项目/空目录'), { recursive: true });
const file = path.join(docs, '报告 $(test) 中文.txt');
await fs.writeFile(file, 'original content');
await fs.writeFile(path.join(docs, '项目/.hidden'), 'hidden content');
await fs.writeFile(path.join(docs, '项目/内容[*]?\n.txt'), 'nested content');
const expected = path.join(docs, '报告 $(test) 中文.zip');
await fs.writeFile(expected, 'existing archive must survive');
let app;
try {
  app = await electron.launch({ colorScheme: null, ...(process.env.EXPLORER_APP_PATH ? { executablePath: process.env.EXPLORER_APP_PATH, args: [] } : { args: [process.cwd()] }), env: { ...process.env, EXPLORER_TEST_ROOT: root, EXPLORER_TEST_HIDDEN: '1' } });
  const page = await app.firstWindow();
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  const entry = page.getByRole('option', { name: path.basename(file), exact: true });
  await entry.waitFor();
  await entry.click({ button: 'right' });
  await page.getByRole('menuitem', { name: '压缩为 ZIP', exact: true }).click();
  const single = path.join(docs, '报告 $(test) 中文 (2).zip');
  await page.getByRole('option', { name: path.basename(single), exact: true }).waitFor();
  assert.equal(await fs.readFile(expected, 'utf8'), 'existing archive must survive');
  assert.equal(await fs.readFile(file, 'utf8'), 'original content');
  const readZip = zip => JSON.parse(execFileSync('/usr/bin/python3', ['-c', 'import zipfile,json,sys\nwith zipfile.ZipFile(sys.argv[1]) as z:\n assert z.testzip() is None\n print(json.dumps({n:z.read(n).decode() for n in z.namelist()},ensure_ascii=True))', zip], { encoding: 'utf8' }));
  const strip = values => Object.fromEntries(Object.entries(values).map(([key, value]) => [key.replace(/^\.\//, ''), value]));
  assert.deepEqual(strip(readZip(single)), { [path.basename(file)]: 'original content' });
  assert.equal((await fs.stat(single)).mode & 0o777, 0o600);
  await page.getByRole('option', { name: '项目', exact: true }).click();
  await entry.click({ modifiers: ['Meta'] });
  await entry.click({ button: 'right' });
  await page.getByRole('menuitem', { name: '压缩为 ZIP', exact: true }).click();
  const multi = path.join(docs, '压缩文件.zip');
  await page.getByRole('option', { name: '压缩文件.zip', exact: true }).waitFor();
  const contents = strip(readZip(multi));
  assert.equal(contents[path.basename(file)], 'original content');
  assert.equal(contents['项目/.hidden'], 'hidden content');
  assert.equal(contents['项目/内容[*]?\n.txt'], 'nested content');
  assert.equal(contents['项目/空目录/'], '');
  assert.equal(Object.keys(contents).length, 5);
  await page.getByRole('option', { name: '压缩文件.zip', exact: true }).dblclick();
  await page.getByRole('dialog').getByRole('button', { name: '项目 文件夹', exact: true }).waitFor();
  await page.keyboard.press('Escape');
  const compress = inputs => page.evaluate(inputs => window.explorer.compressArchive(inputs), inputs);
  const directory = await compress([path.join(docs, '项目')]);
  assert.equal(path.basename(directory), '项目.zip');
  assert.equal(strip(readZip(directory))['项目/.hidden'], 'hidden content');
  const nested = await compress([path.join(docs, '项目'), path.join(docs, '项目/.hidden')]);
  assert.equal(path.basename(nested), '项目 (2).zip');
  assert.deepEqual(strip(readZip(nested)), strip(readZip(directory)));
  const crossing = await compress([file, path.join(docs, '项目/.hidden')]);
  assert.deepEqual(strip(readZip(crossing)), { [path.basename(file)]: 'original content', '项目/.hidden': 'hidden content' });
  // Links must never include files outside the selected source tree.
  await fs.symlink(file, path.join(docs, '项目/link'));
  const before = await fs.readdir(docs);
  await assert.rejects(() => compress([path.join(docs, '项目')]), /链接|特殊/);
  await assert.rejects(() => compress([path.join(docs, '项目/link')]), /链接|特殊/);
  await assert.rejects(() => compress([]), /选择/);
  await assert.rejects(() => compress(['/']), /磁盘/);
  await assert.rejects(() => compress([path.join(docs, 'missing')]), /不存在/);
  assert.deepEqual(await fs.readdir(docs), before);
  assert.equal(await fs.readFile(file, 'utf8'), 'original content');
  assert.equal(await fs.readFile(path.join(docs, '项目/.hidden'), 'utf8'), 'hidden content');
  assert.deepEqual(errors, []);
  console.log('PASS: real right-click single/multiple compression; directory/hidden/empty/Unicode/glob/control names; Python ZIP integrity and app preview; nested deduplication; collision preservation; link/invalid-input failures; no staging leftovers or source changes');
} finally { await app?.close(); await fs.rm(root, { recursive: true, force: true }); }
